DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS products;

CREATE TABLE products (
    id INTEGER PRIMARY KEY,
    name TEXT,         
    description TEXT,  
    price REAL,        
    stock INTEGER,     
    size TEXT,         
    color TEXT,        
    category TEXT      
);

CREATE TABLE carts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cart_id INTEGER,
    product_id INTEGER,
    qty INTEGER DEFAULT 1,
    FOREIGN KEY(cart_id) REFERENCES carts(id),
    FOREIGN KEY(product_id) REFERENCES products(id)
);

INSERT INTO products (id, name, description, price, stock, size, color, category) VALUES 
(1, 'Pantalón Verde', 'Ideal para uso diario.', 1058, 177, 'XXL', 'Verde', 'Deportivo'),
(2, 'Camiseta Blanco', 'Prenda cómoda y ligera.', 510, 33, 'XXL', 'Blanco', 'Deportivo'),
(3, 'Camiseta Negro', 'Diseño moderno y elegante.', 1292, 457, 'S', 'Negro', 'Casual'),
(4, 'Falda Blanco', 'Ideal para uso diario.', 1138, 414, 'S', 'Blanco', 'Casual'),
(5, 'Sudadera Verde', 'Diseño moderno y elegante.', 603, 151, 'XL', 'Verde', 'Formal'),
(6, 'Chaqueta Blanco', 'Material resistente y duradero.', 1391, 296, 'M', 'Blanco', 'Formal'),
(7, 'Camiseta Rojo', 'Diseño moderno y elegante.', 1026, 75, 'L', 'Rojo', 'Casual'),
(8, 'Chaqueta Azul', 'Prenda cómoda y ligera.', 1332, 281, 'S', 'Azul', 'Casual'),
(9, 'Pantalón Negro', 'Ideal para uso diario.', 1222, 117, 'XL', 'Negro', 'Deportivo'),
(10, 'Sudadera Azul', 'Diseño moderno y elegante.', 620, 482, 'XL', 'Azul', 'Formal'),
(11, 'Falda Rojo', 'Material resistente y duradero.', 1282, 332, 'M', 'Rojo', 'Formal'),
(12, 'Pantalón Verde', 'Diseño moderno y elegante.', 808, 420, 'XS', 'Verde', 'Casual'),
(13, 'Sudadera Amarillo', 'Prenda cómoda y ligera.', 827, 269, 'M', 'Amarillo', 'Deportivo'),
(14, 'Falda Negro', 'Diseño moderno y elegante.', 902, 196, 'L', 'Negro', 'Deportivo'),
(15, 'Camiseta Amarillo', 'Ideal para uso diario.', 1085, 203, 'M', 'Amarillo', 'Formal'),
(16, 'Pantalón Rojo', 'Material resistente y duradero.', 1380, 269, 'M', 'Rojo', 'Casual'),
(17, 'Falda Azul', 'Prenda cómoda y ligera.', 854, 460, 'M', 'Azul', 'Casual'),
(18, 'Pantalón Blanco', 'Diseño moderno y elegante.', 717, 33, 'S', 'Blanco', 'Formal'),
(19, 'Falda Negro', 'Material resistente y duradero.', 862, 193, 'XXL', 'Negro', 'Formal'),
(20, 'Sudadera Azul', 'Diseño moderno y elegante.', 782, 371, 'S', 'Azul', 'Deportivo'),
(21, 'Pantalón Verde', 'Material resistente y duradero.', 1188, 321, 'XL', 'Verde', 'Formal'),
(22, 'Chaqueta Rojo', 'Prenda cómoda y ligera.', 715, 303, 'XXL', 'Rojo', 'Deportivo'),
(23, 'Sudadera Rojo', 'Diseño moderno y elegante.', 619, 463, 'M', 'Rojo', 'Deportivo'),
(24, 'Chaqueta Negro', 'Prenda cómoda y ligera.', 1118, 59, 'XL', 'Negro', 'Deportivo'),
(25, 'Chaqueta Negro', 'Material resistente y duradero.', 562, 298, 'XL', 'Negro', 'Formal'),
(26, 'Camiseta Blanco', 'Diseño moderno y elegante.', 574, 18, 'S', 'Blanco', 'Formal'),
(27, 'Falda Verde', 'Diseño moderno y elegante.', 1383, 313, 'M', 'Verde', 'Deportivo'),
(28, 'Sudadera Blanco', 'Material resistente y duradero.', 1238, 206, 'XS', 'Blanco', 'Deportivo'),
(29, 'Camiseta Verde', 'Prenda cómoda y ligera.', 982, 401, 'XL', 'Verde', 'Casual'),
(30, 'Sudadera Amarillo', 'Material resistente y duradero.', 1335, 344, 'XS', 'Amarillo', 'Casual'),
(31, 'Falda Verde', 'Diseño moderno y elegante.', 1344, 179, 'S', 'Verde', 'Deportivo'),
(32, 'Sudadera Azul', 'Diseño moderno y elegante.', 1162, 281, 'S', 'Azul', 'Deportivo'),
(33, 'Sudadera Negro', 'Prenda cómoda y ligera.', 656, 177, 'M', 'Negro', 'Formal'),
(34, 'Falda Rojo', 'Prenda cómoda y ligera.', 1445, 12, 'XS', 'Rojo', 'Deportivo'),
(35, 'Camiseta Azul', 'Diseño moderno y elegante.', 1176, 276, 'XXL', 'Azul', 'Deportivo'),
(36, 'Camiseta Amarillo', 'Diseño moderno y elegante.', 840, 489, 'S', 'Amarillo', 'Formal'),
(37, 'Falda Verde', 'Ideal para uso diario.', 857, 439, 'XL', 'Verde', 'Casual'),
(38, 'Chaqueta Rojo', 'Diseño moderno y elegante.', 704, 307, 'L', 'Rojo', 'Deportivo'),
(39, 'Pantalón Amarillo', 'Material resistente y duradero.', 598, 402, 'S', 'Amarillo', 'Formal'),
(40, 'Falda Azul', 'Material resistente y duradero.', 1269, 137, 'XS', 'Azul', 'Deportivo'),
(41, 'Chaqueta Verde', 'Material resistente y duradero.', 1159, 114, 'XXL', 'Verde', 'Formal'),
(42, 'Falda Verde', 'Prenda cómoda y ligera.', 644, 461, 'XS', 'Verde', 'Formal'),
(43, 'Falda Negro', 'Material resistente y duradero.', 947, 465, 'S', 'Negro', 'Deportivo'),
(44, 'Chaqueta Rojo', 'Prenda cómoda y ligera.', 951, 102, 'XS', 'Rojo', 'Deportivo'),
(45, 'Pantalón Verde', 'Material resistente y duradero.', 1251, 10, 'S', 'Verde', 'Formal'),
(46, 'Falda Blanco', 'Prenda cómoda y ligera.', 645, 237, 'M', 'Blanco', 'Formal'),
(47, 'Camiseta Negro', 'Prenda cómoda y ligera.', 1289, 442, 'XS', 'Negro', 'Casual'),
(48, 'Pantalón Azul', 'Material resistente y duradero.', 678, 14, 'M', 'Azul', 'Casual'),
(49, 'Chaqueta Rojo', 'Material resistente y duradero.', 509, 362, 'S', 'Rojo', 'Deportivo'),
(50, 'Falda Negro', 'Material resistente y duradero.', 1109, 290, 'L', 'Negro', 'Formal'),
(51, 'Sudadera Verde', 'Ideal para uso diario.', 633, 498, 'XS', 'Verde', 'Deportivo'),
(52, 'Sudadera Negro', 'Prenda cómoda y ligera.', 804, 335, 'XXL', 'Negro', 'Deportivo'),
(53, 'Camiseta Negro', 'Material resistente y duradero.', 528, 493, 'L', 'Negro', 'Deportivo'),
(54, 'Chaqueta Verde', 'Ideal para uso diario.', 743, 234, 'XS', 'Verde', 'Deportivo'),
(55, 'Camiseta Verde', 'Prenda cómoda y ligera.', 1450, 483, 'L', 'Verde', 'Deportivo'),
(56, 'Chaqueta Verde', 'Material resistente y duradero.', 1445, 12, 'L', 'Verde', 'Casual'),
(57, 'Camiseta Blanco', 'Material resistente y duradero.', 1083, 149, 'XS', 'Blanco', 'Casual'),
(58, 'Camiseta Blanco', 'Material resistente y duradero.', 861, 353, 'S', 'Blanco', 'Formal'),
(59, 'Falda Azul', 'Ideal para uso diario.', 813, 145, 'S', 'Azul', 'Formal'),
(60, 'Sudadera Rojo', 'Diseño moderno y elegante.', 862, 281, 'S', 'Rojo', 'Formal'),
(61, 'Pantalón Amarillo', 'Prenda cómoda y ligera.', 1121, 196, 'XS', 'Amarillo', 'Deportivo'),
(62, 'Falda Negro', 'Ideal para uso diario.', 1114, 252, 'XS', 'Negro', 'Formal'),
(63, 'Camiseta Negro', 'Ideal para uso diario.', 1446, 219, 'S', 'Negro', 'Deportivo'),
(64, 'Pantalón Azul', 'Ideal para uso diario.', 1024, 69, 'XL', 'Azul', 'Deportivo'),
(65, 'Sudadera Blanco', 'Material resistente y duradero.', 680, 246, 'S', 'Blanco', 'Deportivo'),
(66, 'Falda Blanco', 'Material resistente y duradero.', 529, 39, 'M', 'Blanco', 'Casual'),
(67, 'Falda Negro', 'Ideal para uso diario.', 1318, 303, 'XL', 'Negro', 'Formal'),
(68, 'Sudadera Azul', 'Diseño moderno y elegante.', 520, 269, 'L', 'Azul', 'Casual'),
(69, 'Pantalón Amarillo', 'Ideal para uso diario.', 754, 465, 'L', 'Amarillo', 'Casual'),
(70, 'Camiseta Azul', 'Diseño moderno y elegante.', 1014, 460, 'XS', 'Azul', 'Formal'),
(71, 'Sudadera Verde', 'Ideal para uso diario.', 857, 107, 'L', 'Verde', 'Formal'),
(72, 'Camiseta Rojo', 'Ideal para uso diario.', 1421, 37, 'S', 'Rojo', 'Casual'),
(73, 'Camiseta Rojo', 'Material resistente y duradero.', 1395, 332, 'M', 'Rojo', 'Formal'),
(74, 'Camiseta Amarillo', 'Ideal para uso diario.', 1450, 436, 'M', 'Amarillo', 'Deportivo'),
(75, 'Camiseta Amarillo', 'Material resistente y duradero.', 729, 375, 'XS', 'Amarillo', 'Formal'),
(76, 'Pantalón Rojo', 'Ideal para uso diario.', 1481, 335, 'S', 'Rojo', 'Deportivo'),
(77, 'Falda Rojo', 'Prenda cómoda y ligera.', 653, 319, 'S', 'Rojo', 'Formal'),
(78, 'Pantalón Negro', 'Diseño moderno y elegante.', 1045, 114, 'XS', 'Negro', 'Deportivo'),
(79, 'Sudadera Azul', 'Ideal para uso diario.', 1175, 237, 'XXL', 'Azul', 'Casual'),
(80, 'Pantalón Rojo', 'Prenda cómoda y ligera.', 902, 427, 'L', 'Rojo', 'Formal'),
(81, 'Pantalón Azul', 'Ideal para uso diario.', 1198, 484, 'S', 'Azul', 'Formal'),
(82, 'Sudadera Amarillo', 'Prenda cómoda y ligera.', 1178, 115, 'XS', 'Amarillo', 'Casual'),
(83, 'Chaqueta Amarillo', 'Material resistente y duradero.', 1310, 392, 'L', 'Amarillo', 'Casual'),
(84, 'Camiseta Rojo', 'Ideal para uso diario.', 1221, 460, 'S', 'Rojo', 'Deportivo'),
(85, 'Chaqueta Blanco', 'Prenda cómoda y ligera.', 513, 360, 'XXL', 'Blanco', 'Deportivo'),
(86, 'Camiseta Amarillo', 'Diseño moderno y elegante.', 1475, 411, 'S', 'Amarillo', 'Casual'),
(87, 'Sudadera Negro', 'Prenda cómoda y ligera.', 1390, 482, 'S', 'Negro', 'Casual'),
(88, 'Camiseta Blanco', 'Ideal para uso diario.', 609, 137, 'S', 'Blanco', 'Deportivo'),
(89, 'Sudadera Amarillo', 'Material resistente y duradero.', 527, 429, 'S', 'Amarillo', 'Casual'),
(90, 'Pantalón Verde', 'Diseño moderno y elegante.', 860, 240, 'M', 'Verde', 'Casual'),
(91, 'Pantalón Negro', 'Ideal para uso diario.', 926, 426, 'S', 'Negro', 'Formal'),
(92, 'Falda Blanco', 'Diseño moderno y elegante.', 934, 497, 'XS', 'Blanco', 'Formal'),
(93, 'Falda Amarillo', 'Diseño moderno y elegante.', 1109, 39, 'M', 'Amarillo', 'Deportivo'),
(94, 'Falda Blanco', 'Material resistente y duradero.', 1403, 107, 'L', 'Blanco', 'Deportivo'),
(95, 'Camiseta Amarillo', 'Prenda cómoda y ligera.', 1148, 179, 'XS', 'Amarillo', 'Formal'),
(96, 'Falda Verde', 'Diseño moderno y elegante.', 944, 18, 'M', 'Verde', 'Casual'),
(97, 'Falda Amarillo', 'Ideal para uso diario.', 857, 12, 'S', 'Amarillo', 'Formal'),
(98, 'Chaqueta Verde', 'Ideal para uso diario.', 1450, 439, 'M', 'Verde', 'Formal'),
(99, 'Pantalón Blanco', 'Diseño moderno y elegante.', 704, 252, 'L', 'Blanco', 'Casual'),
(100, 'Sudadera Blanco', 'Material resistente y duradero.', 598, 402, 'S', 'Blanco', 'Deportivo');